name: build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PDF

    steps:
      - uses: actions/checkout@v3

      - name: Setup TeX Live
        run: |
          sudo apt-get install -y \
          texlive-latex-base texlive-fonts-recommended \
          texlive-fonts-extra texlive-latex-extra \
          texlive-lang-german make

      - name: Build PDF
        run: make

      - name: Create GitHub Release with PDF
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.pdf


